// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/gardens": {
    params: {};
  };
  "/gardens/new": {
    params: {};
  };
  "/gardens/:gardenSlug": {
    params: {
      "gardenSlug": string;
    };
  };
  "/gardens/:gardenSlug/edit": {
    params: {
      "gardenSlug": string;
    };
  };
  "/gardens/:gardenSlug/plants/:plantId": {
    params: {
      "gardenSlug": string;
      "plantId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/register" | "/auth/logout" | "/admin/users" | "/gardens" | "/gardens/new" | "/gardens/:gardenSlug" | "/gardens/:gardenSlug/edit" | "/gardens/:gardenSlug/plants/:plantId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/admin/users" | "/gardens" | "/gardens/new" | "/gardens/:gardenSlug" | "/gardens/:gardenSlug/edit" | "/gardens/:gardenSlug/plants/:plantId";
  };
  "routes/_app.admin.users.tsx": {
    id: "routes/_app.admin.users";
    page: "/admin/users";
  };
  "routes/_app.gardens.tsx": {
    id: "routes/_app.gardens";
    page: "/gardens";
  };
  "routes/_app.gardens.new.tsx": {
    id: "routes/_app.gardens.new";
    page: "/gardens/new";
  };
  "routes/_app.gardens.$gardenSlug.tsx": {
    id: "routes/_app.gardens.$gardenSlug";
    page: "/gardens/:gardenSlug" | "/gardens/:gardenSlug/edit" | "/gardens/:gardenSlug/plants/:plantId";
  };
  "routes/_app.gardens.$gardenSlug._index.tsx": {
    id: "routes/_app.gardens.$gardenSlug._index";
    page: "/gardens/:gardenSlug";
  };
  "routes/_app.gardens.$gardenSlug.edit.tsx": {
    id: "routes/_app.gardens.$gardenSlug.edit";
    page: "/gardens/:gardenSlug/edit";
  };
  "routes/_app.gardens.$gardenSlug.plants.$plantId.tsx": {
    id: "routes/_app.gardens.$gardenSlug.plants.$plantId";
    page: "/gardens/:gardenSlug/plants/:plantId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.register": typeof import("./app/routes/auth.register.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app.admin.users": typeof import("./app/routes/_app.admin.users.tsx");
  "routes/_app.gardens": typeof import("./app/routes/_app.gardens.tsx");
  "routes/_app.gardens.new": typeof import("./app/routes/_app.gardens.new.tsx");
  "routes/_app.gardens.$gardenSlug": typeof import("./app/routes/_app.gardens.$gardenSlug.tsx");
  "routes/_app.gardens.$gardenSlug._index": typeof import("./app/routes/_app.gardens.$gardenSlug._index.tsx");
  "routes/_app.gardens.$gardenSlug.edit": typeof import("./app/routes/_app.gardens.$gardenSlug.edit.tsx");
  "routes/_app.gardens.$gardenSlug.plants.$plantId": typeof import("./app/routes/_app.gardens.$gardenSlug.plants.$plantId.tsx");
};