// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/auth/forgot-password": {
    params: {};
  };
  "/auth/reset-password": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/feedback": {
    params: {};
  };
  "/help": {
    params: {};
  };
  "/help/gardens": {
    params: {};
  };
  "/help/plants": {
    params: {};
  };
  "/help/notes": {
    params: {};
  };
  "/help/harvests": {
    params: {};
  };
  "/help/ai-tips": {
    params: {};
  };
  "/help/account": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/gardens": {
    params: {};
  };
  "/admin/invitations": {
    params: {};
  };
  "/invitations/:token": {
    params: {
      "token": string;
    };
  };
  "/gardens": {
    params: {};
  };
  "/gardens/new": {
    params: {};
  };
  "/gardens/:gardenSlug": {
    params: {
      "gardenSlug": string;
    };
  };
  "/gardens/:gardenSlug/edit": {
    params: {
      "gardenSlug": string;
    };
  };
  "/gardens/:gardenSlug/members": {
    params: {
      "gardenSlug": string;
    };
  };
  "/gardens/:gardenSlug/plants/:plantId": {
    params: {
      "gardenSlug": string;
      "plantId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/register" | "/auth/login" | "/auth/register" | "/auth/logout" | "/auth/forgot-password" | "/auth/reset-password" | "/settings" | "/feedback" | "/help" | "/help/gardens" | "/help/plants" | "/help/notes" | "/help/harvests" | "/help/ai-tips" | "/help/account" | "/admin" | "/admin/users" | "/admin/gardens" | "/admin/invitations" | "/invitations/:token" | "/gardens" | "/gardens/new" | "/gardens/:gardenSlug" | "/gardens/:gardenSlug/edit" | "/gardens/:gardenSlug/members" | "/gardens/:gardenSlug/plants/:plantId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/register-redirect.tsx": {
    id: "routes/register-redirect";
    page: "/register";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/auth.forgot-password.tsx": {
    id: "routes/auth.forgot-password";
    page: "/auth/forgot-password";
  };
  "routes/auth.reset-password.tsx": {
    id: "routes/auth.reset-password";
    page: "/auth/reset-password";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/settings" | "/feedback" | "/help" | "/help/gardens" | "/help/plants" | "/help/notes" | "/help/harvests" | "/help/ai-tips" | "/help/account" | "/admin" | "/admin/users" | "/admin/gardens" | "/admin/invitations" | "/invitations/:token" | "/gardens" | "/gardens/new" | "/gardens/:gardenSlug" | "/gardens/:gardenSlug/edit" | "/gardens/:gardenSlug/members" | "/gardens/:gardenSlug/plants/:plantId";
  };
  "routes/_app.settings.tsx": {
    id: "routes/_app.settings";
    page: "/settings";
  };
  "routes/_app.feedback.tsx": {
    id: "routes/_app.feedback";
    page: "/feedback";
  };
  "routes/_app.help.tsx": {
    id: "routes/_app.help";
    page: "/help" | "/help/gardens" | "/help/plants" | "/help/notes" | "/help/harvests" | "/help/ai-tips" | "/help/account";
  };
  "routes/_app.help._index.tsx": {
    id: "routes/_app.help._index";
    page: "/help";
  };
  "routes/_app.help.gardens.tsx": {
    id: "routes/_app.help.gardens";
    page: "/help/gardens";
  };
  "routes/_app.help.plants.tsx": {
    id: "routes/_app.help.plants";
    page: "/help/plants";
  };
  "routes/_app.help.notes.tsx": {
    id: "routes/_app.help.notes";
    page: "/help/notes";
  };
  "routes/_app.help.harvests.tsx": {
    id: "routes/_app.help.harvests";
    page: "/help/harvests";
  };
  "routes/_app.help.ai-tips.tsx": {
    id: "routes/_app.help.ai-tips";
    page: "/help/ai-tips";
  };
  "routes/_app.help.account.tsx": {
    id: "routes/_app.help.account";
    page: "/help/account";
  };
  "routes/_app.admin.tsx": {
    id: "routes/_app.admin";
    page: "/admin" | "/admin/users" | "/admin/gardens" | "/admin/invitations";
  };
  "routes/_app.admin._index.tsx": {
    id: "routes/_app.admin._index";
    page: "/admin";
  };
  "routes/_app.admin.users.tsx": {
    id: "routes/_app.admin.users";
    page: "/admin/users";
  };
  "routes/_app.admin.gardens.tsx": {
    id: "routes/_app.admin.gardens";
    page: "/admin/gardens";
  };
  "routes/_app.admin.invitations.tsx": {
    id: "routes/_app.admin.invitations";
    page: "/admin/invitations";
  };
  "routes/_app.invitations.$token.tsx": {
    id: "routes/_app.invitations.$token";
    page: "/invitations/:token";
  };
  "routes/_app.gardens.tsx": {
    id: "routes/_app.gardens";
    page: "/gardens";
  };
  "routes/_app.gardens.new.tsx": {
    id: "routes/_app.gardens.new";
    page: "/gardens/new";
  };
  "routes/_app.gardens.$gardenSlug.tsx": {
    id: "routes/_app.gardens.$gardenSlug";
    page: "/gardens/:gardenSlug" | "/gardens/:gardenSlug/edit" | "/gardens/:gardenSlug/members" | "/gardens/:gardenSlug/plants/:plantId";
  };
  "routes/_app.gardens.$gardenSlug._index.tsx": {
    id: "routes/_app.gardens.$gardenSlug._index";
    page: "/gardens/:gardenSlug";
  };
  "routes/_app.gardens.$gardenSlug.edit.tsx": {
    id: "routes/_app.gardens.$gardenSlug.edit";
    page: "/gardens/:gardenSlug/edit";
  };
  "routes/_app.gardens.$gardenSlug.members.tsx": {
    id: "routes/_app.gardens.$gardenSlug.members";
    page: "/gardens/:gardenSlug/members";
  };
  "routes/_app.gardens.$gardenSlug.plants.$plantId.tsx": {
    id: "routes/_app.gardens.$gardenSlug.plants.$plantId";
    page: "/gardens/:gardenSlug/plants/:plantId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/register-redirect": typeof import("./app/routes/register-redirect.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.register": typeof import("./app/routes/auth.register.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/auth.forgot-password": typeof import("./app/routes/auth.forgot-password.tsx");
  "routes/auth.reset-password": typeof import("./app/routes/auth.reset-password.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app.settings": typeof import("./app/routes/_app.settings.tsx");
  "routes/_app.feedback": typeof import("./app/routes/_app.feedback.tsx");
  "routes/_app.help": typeof import("./app/routes/_app.help.tsx");
  "routes/_app.help._index": typeof import("./app/routes/_app.help._index.tsx");
  "routes/_app.help.gardens": typeof import("./app/routes/_app.help.gardens.tsx");
  "routes/_app.help.plants": typeof import("./app/routes/_app.help.plants.tsx");
  "routes/_app.help.notes": typeof import("./app/routes/_app.help.notes.tsx");
  "routes/_app.help.harvests": typeof import("./app/routes/_app.help.harvests.tsx");
  "routes/_app.help.ai-tips": typeof import("./app/routes/_app.help.ai-tips.tsx");
  "routes/_app.help.account": typeof import("./app/routes/_app.help.account.tsx");
  "routes/_app.admin": typeof import("./app/routes/_app.admin.tsx");
  "routes/_app.admin._index": typeof import("./app/routes/_app.admin._index.tsx");
  "routes/_app.admin.users": typeof import("./app/routes/_app.admin.users.tsx");
  "routes/_app.admin.gardens": typeof import("./app/routes/_app.admin.gardens.tsx");
  "routes/_app.admin.invitations": typeof import("./app/routes/_app.admin.invitations.tsx");
  "routes/_app.invitations.$token": typeof import("./app/routes/_app.invitations.$token.tsx");
  "routes/_app.gardens": typeof import("./app/routes/_app.gardens.tsx");
  "routes/_app.gardens.new": typeof import("./app/routes/_app.gardens.new.tsx");
  "routes/_app.gardens.$gardenSlug": typeof import("./app/routes/_app.gardens.$gardenSlug.tsx");
  "routes/_app.gardens.$gardenSlug._index": typeof import("./app/routes/_app.gardens.$gardenSlug._index.tsx");
  "routes/_app.gardens.$gardenSlug.edit": typeof import("./app/routes/_app.gardens.$gardenSlug.edit.tsx");
  "routes/_app.gardens.$gardenSlug.members": typeof import("./app/routes/_app.gardens.$gardenSlug.members.tsx");
  "routes/_app.gardens.$gardenSlug.plants.$plantId": typeof import("./app/routes/_app.gardens.$gardenSlug.plants.$plantId.tsx");
};